# Generated by Django 5.0.4 on 2024-05-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedas',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
